// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgdJMkNBQ5S5mRbAI_1P3D1LL4bUh9yM',
    appId: '1:473610286696:web:6156f5a4eafb1fdc52addd',
    messagingSenderId: '473610286696',
    projectId: 'salesfollowup-7557c',
    authDomain: 'salesfollowup-7557c.firebaseapp.com',
    storageBucket: 'salesfollowup-7557c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYGcxjzFek8t-dYniD42JoE3UjvyL6sQ',
    appId: '1:473610286696:android:6cf0add9faf9948a52addd',
    messagingSenderId: '473610286696',
    projectId: 'salesfollowup-7557c',
    storageBucket: 'salesfollowup-7557c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVeFppJQK7-EXmrpeVYKV-jFjCcwDI29Q',
    appId: '1:473610286696:ios:4660d414e89babbf52addd',
    messagingSenderId: '473610286696',
    projectId: 'salesfollowup-7557c',
    storageBucket: 'salesfollowup-7557c.firebasestorage.app',
    iosBundleId: 'com.example.salestool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgdJMkNBQ5S5mRbAI_1P3D1LL4bUh9yM',
    appId: '1:473610286696:web:92c4e96ddbe432b552addd',
    messagingSenderId: '473610286696',
    projectId: 'salesfollowup-7557c',
    authDomain: 'salesfollowup-7557c.firebaseapp.com',
    storageBucket: 'salesfollowup-7557c.firebasestorage.app',
  );
}
